# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da99b20f8f11459fb243057c47f4b17d2fe7a4522cdd8a82c9d9581acf9f65e295ccc392056d2fb974dd61baa582ea4d14bfe0eb4acd718cba01a6c9b01da189

test:
  secret_key_base: f452fcfe5c2a1e650ffc4b89ba9e1e8741b7b27e0b0c54cd2b05580cd5673af7e2e782318b1ad599902d3082fa0132210a25270e79fb6b962b3c734107d6cccd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
